services:
  db:
    image: postgres
    volumes:
    # - ./tmp/db:/var/lib/postgresql/data
    - type: volume
      source: mydata
      target: /var/lib/postgresql/data
      volume:
        nocopy: true
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && rails db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
version: '3.7'

volumes:
  mydata: