services:
  db:
    image: postgres
    volumes:
    - type: volume
      source: mydata
      target: /var/lib/postgresql/data
      volume:
        nocopy: true
    # ports:
    #   - "5432:5432"
  web:
    build: .
      # context: .
      # dockerfile: Dockerfile-build
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: /bin/bash
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
version: '3.7'

volumes:
  mydata: